version: '3'

services:
  postgis:
    image: ${POSTGIS_IMAGE}
    container_name: ${PROJECT_PREFIX}_postgis
    env_file: 
      - ./envs/postgis.env
    volumes: 
      - postgis_data:/var/lib/postgresql/data
    hostname: ${PROJECT_PREFIX}_postgis
    networks:
      - db_network
    ports: 
      - 5432:5432

networks: 
  db_network:

volumes: 
  postgis_data: