version: '3'

services:
  postgrest:
    image: ${POSTGREST_IMAGE}
    container_name: ${PROJECT_PREFIX}_postgrest
    env_file:
      - ./envs/postgrest.env
    depends_on:
      - postgis
    hostname: ${PROJECT_PREFIX}_postgrest
    networks:
      - db_network
    ports:
      - 3000:3000
  
  # swagger:
  #   image: ${SWAGGER_IMAGE}
  #   container_name: ${PROJECT_PREFIX}_swagger
  #   env_file:
  #     - ./envs/swagger.env
  #   depends_on:
  #     - postgrest
  #   hostname: ${PROJECT_PREFIX}_swagger
  #   networks:
  #     - db_network
  #   ports:
  #     - "8080:8080"
