version: '3'

services:
  postgis:
    volumes: 
      - ./dev/data:/work
    working_dir: /work
  
  postgrest:
    ports:
      - 3000:3000

  pgadmin:
    image: ${PGADMIN_IMAGE}
    container_name: ${PROJECT_PREFIX}_pgadmin4
    env_file:
      - envs/pgadmin.env
    volumes: 
      - ./dev/sql:/var/lib/pgadmin/storage
    depends_on:
      - postgis
    hostname: ${PROJECT_PREFIX}_pgadmin4
    networks: 
      - db_network
    ports: 
      - 5050:80
  
  kit:
    image: ${NODE_IMAGE}
    volumes: 
      - ./kit/app:/app
    working_dir: /app
    ports:
      - 5173:5173

