version: '3'

services:
  postgis:
    volumes: 
      - ./dev/data:/work
    working_dir: /work

  pgadmin:
    image: ${PGADMIN_IMAGE}
    container_name: ${PROJECT_PREFIX}_pgadmin4
    env_file:
      - envs/pgadmin.env
    volumes: 
      - ./dev/sql:/var/lib/pgadmin/storage
    depends_on:
      - postgis
    hostname: ${PROJECT_PREFIX}_pgadmin4
    networks: 
      - db_network
    ports: 
      - 5050:80
