DROP SCHEMA IF EXISTS auth CASCADE;
DROP SCHEMA IF EXISTS api CASCADE;
DROP SCHEMA IF EXISTS amy CASCADE;
DROP SCHEMA IF EXISTS elisabeth CASCADE;
DROP SCHEMA IF EXISTS isabel CASCADE;
DROP SCHEMA IF EXISTS joe CASCADE;
DROP SCHEMA IF EXISTS joed CASCADE;

DROP EXTENSION IF EXISTS citext;
DROP EXTENSION IF EXISTS pgjwt;
DROP EXTENSION IF EXISTS pgcrypto;

DROP ROLE IF EXISTS authenticator;
DROP ROLE IF EXISTS anonymous;
DROP ROLE IF EXISTS web_user;
DROP ROLE IF EXISTS api_views_owner;
DROP ROLE IF EXISTS amy;
DROP ROLE IF EXISTS elisabeth;
DROP ROLE IF EXISTS isabel;
DROP ROLE IF EXISTS joe;
DROP ROLE IF EXISTS joed;